"use strict";

// Where uploaded export files live.
//
// Same move as StorageAdapter, one layer over: the API stores blobs through an
// interface, so "local disk" today and "S3/R2" later is a new class rather than
// a rewrite. docs/01-DECISIONS.md picked a VPS, and a VPS has a disk; when the
// service outgrows one machine the app changes in exactly one place.
//
// Keys are opaque strings generated HERE, never derived from user input. A
// filename that arrives over HTTP is display metadata and nothing else — the
// moment it can influence a path, `../../etc/passwd` becomes a valid upload.

const fs = require("node:fs/promises");
const fsSync = require("node:fs");
const path = require("node:path");
const crypto = require("node:crypto");

class BlobStore {
  /** @param {Buffer} data @returns {Promise<string>} the key to store in the DB */
  async put(data) { throw new Error("BlobStore.put not implemented"); }
  /** @param {string} key @returns {Promise<Buffer>} */
  async get(key) { throw new Error("BlobStore.get not implemented"); }
  /** @param {string} key @returns {Promise<void>} — deleting a missing key is fine */
  async delete(key) { throw new Error("BlobStore.delete not implemented"); }
  /** @param {string} key @returns {Promise<boolean>} */
  async exists(key) { throw new Error("BlobStore.exists not implemented"); }
}

/** Blobs as files under one directory. */
class LocalBlobStore extends BlobStore {
  /** @param {string} rootDir */
  constructor(rootDir) {
    super();
    this.rootDir = path.resolve(rootDir);
    fsSync.mkdirSync(this.rootDir, { recursive: true });
  }

  /**
   * Keys are `<yyyy-mm>/<32 hex chars>`: random, unguessable, and sharded by
   * month so no single directory ends up with a million entries.
   */
  #newKey() {
    const month = new Date().toISOString().slice(0, 7);
    return `${month}/${crypto.randomBytes(16).toString("hex")}`;
  }

  /**
   * Resolve a key to a path, refusing anything that escapes the root.
   *
   * Keys are generated by this class, so a bad one means either a bug or a
   * tampered database row. Either way the answer is to refuse, not to trust the
   * caller — this is the check that makes `..` in a key harmless.
   */
  #pathFor(key) {
    if (typeof key !== "string" || key.length === 0) {
      throw new Error("blob key must be a non-empty string");
    }
    const full = path.resolve(this.rootDir, key);
    if (full !== this.rootDir && !full.startsWith(this.rootDir + path.sep)) {
      throw new Error(`blob key escapes the store root: ${key}`);
    }
    return full;
  }

  async put(data) {
    const key = this.#newKey();
    const full = this.#pathFor(key);
    await fs.mkdir(path.dirname(full), { recursive: true });
    await fs.writeFile(full, data);
    return key;
  }

  async get(key) {
    return fs.readFile(this.#pathFor(key));
  }

  async delete(key) {
    await fs.rm(this.#pathFor(key), { force: true });
  }

  async exists(key) {
    try {
      await fs.access(this.#pathFor(key));
      return true;
    } catch {
      return false;
    }
  }
}

module.exports = { BlobStore, LocalBlobStore };
